### ISSUE TITLE
message hammer of righteous

### ISSUE THREAD

**Issue by matton300** [kaminaris/MaxDps-Paladin#4]
HI, i have blessed hammer and i shouldn't get the message that i dont have hammer of righteous on action bar. thanks

**Comment by seqwith** [comment]
I found a fix to this I had to change lines 103, 104 to correct this issue.

if talents[PR.BlessedHammer] and cooldown[PR.BlessedHammer].ready then
		return PR.BlessedHammer;

elseif cooldown[PR.HammerOfTheRighteous].ready then
		return PR.HammerOfTheRighteous;
end
